fix(ddns): fix formatting

diff --git a/cluster/apps/networking/cloudflare-ddns/cron-job.yaml b/cluster/apps/networking/cloudflare-ddns/cron-job.yaml
--- a/cluster/apps/networking/cloudflare-ddns/cron-job.yaml
+++ b/cluster/apps/networking/cloudflare-ddns/cron-job.yaml
@@ -1,5 +1,5 @@
 ---
-apiVersion: batch/v1beta1
+apiVersion: batch/v1
 kind: CronJob
 metadata:
   name: cloudflare-ddns
@@ -16,47 +16,46 @@ spec:
           restartPolicy: Never
           hostNetwork: true
           containers:
-          - name: cloudflare-ddns
-            image: curlimages/curl:7.76.1
-            envFrom:
-            - secretRef:
-                name: cloudflare-ddns
-            command:
-            - /bin/sh
-            - -c
-            - |
-              echo "starting script"
-              set -o nounset
-              set -o errexit
-              ip4=$(curl https://ipv4.icanhazip.com/)
-              echo "my ipv4 is $ipv4"
-              record4=$(curl -s -X GET \
-                "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONEID/dns_records?name=$CLOUDFLARE_RECORD_NAME&type=A" \
-                -H "X-Auth-Email: $CLOUDFLARE_EMAIL" \
-                -H "X-Auth-Key: $CLOUDFLARE_APIKEY" \
-                -H "Content-Type: application/json" \
-              )
-              echo "my record from cloudflare is $record4"
-              old_ip4=$(echo "$record4" | sed -n 's/.*"content":"\([^"]*\).*/\1/p')
-              if [ "$ip4" = "$old_ip4" ]; then
-                printf "%s - Success - IP Address '%s' has not changed" "$(date -u)" "$ip4"
-                exit 0
-              fi
-              echo "my old ipv4 is $old_ipv4"
-              record4_identifier=$(echo "$record4" | sed -n 's/.*"id":"\([^"]*\).*/\1/p')
-              echo "my record 4 identifier is $record4_identifier"
-              update4=$(curl -s -X PUT \
-                "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONEID/dns_records/$record4_identifier" \
-                -H "X-Auth-Email: $CLOUDFLARE_EMAIL" \
-                -H "X-Auth-Key: $CLOUDFLARE_APIKEY" \
-                -H "Content-Type: application/json" \
-                --data "{\"id\":\"$CLOUDFLARE_ZONEID\",\"type\":\"A\",\"proxied\":true,\"name\":\"$CLOUDFLARE_RECORD_NAME\",\"content\":\"$ip4\"}" \
-              )
-              echo "my update4 is $update4"
-              if echo "$update4" | grep -q '\"success\":false'; then
-                printf "%s - Yikes - Updating IP Address '%s' has failed" "$(date -u)" "$ip4"
-                exit 1
-              else
-                printf "%s - Success - IP Address '%s' has been updated" "$(date -u)" "$ip4"
-                exit 0
-              fi
+            - name: cloudflare-ddns
+              image: curlimages/curl:7.76.1
+              imagePullPolicy: IfNotPresent
+              envFrom:
+              - secretRef:
+                  name: cloudflare-ddns
+              command: ["/bin/sh", "-c"]
+              args: 
+              - echo "starting script"
+                set -o nounset
+                set -o errexit
+                ipv4=$(curl https://ipv4.icanhazip.com/)
+                echo "my ipv4 is $ipv4"
+                record4=$(curl -s -X GET \
+                  "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONEID/dns_records?name=$CLOUDFLARE_RECORD_NAME&type=A" \
+                  -H "X-Auth-Email: $CLOUDFLARE_EMAIL" \
+                  -H "X-Auth-Key: $CLOUDFLARE_APIKEY" \
+                  -H "Content-Type: application/json" \
+                )
+                echo "my record from cloudflare is $record4"
+                old_ipv4=$(echo "$record4" | sed -n 's/.*"content":"\([^"]*\).*/\1/p')
+                if [ "$ipv4" = "$old_ipv4" ]; then
+                  printf "%s - Success - IP Address '%s' has not changed" "$(date -u)" "$ipv4"
+                  exit 0
+                fi
+                echo "my old ipv4 is $old_ipv4"
+                record4_identifier=$(echo "$record4" | sed -n 's/.*"id":"\([^"]*\).*/\1/p')
+                echo "my record 4 identifier is $record4_identifier"
+                update4=$(curl -s -X PUT \
+                  "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONEID/dns_records/$record4_identifier" \
+                  -H "X-Auth-Email: $CLOUDFLARE_EMAIL" \
+                  -H "X-Auth-Key: $CLOUDFLARE_APIKEY" \
+                  -H "Content-Type: application/json" \
+                  --data "{\"id\":\"$CLOUDFLARE_ZONEID\",\"type\":\"A\",\"proxied\":true,\"name\":\"$CLOUDFLARE_RECORD_NAME\",\"content\":\"$ipv4\"}" \
+                )
+                echo "my update4 is $update4"
+                if echo "$update4" | grep -q '\"success\":false'; then
+                  printf "%s - Yikes - Updating IP Address '%s' has failed" "$(date -u)" "$ipv4"
+                  exit 1
+                else
+                  printf "%s - Success - IP Address '%s' has been updated" "$(date -u)" "$ipv4"
+                  exit 0
+                fi
